#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser and the opencode CLI; this wizard tells you exactly\n' "$DIM"
  printf '  what to do and verifies the result. Stop any time with Ctrl-C and re-run\n'
  printf '  later.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — provisions one more isolated OpenCode Go identity per run.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

DEFAULT_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
DEFAULT_AUTH="$DEFAULT_DATA_HOME/opencode/auth.json"

banner "Add another OpenCode Go account"

# ── Stage 1: the second (or Nth) account itself, in the browser ───────────
stage "A separate opencode.ai account, subscribed to Go"
say "opencode keeps every provider credential in one auth.json per data directory,"
say "keyed by provider name — so it can only ever hold ONE Go key at a time."
say "A second concurrent subscription needs a second opencode.ai account, with"
say "its own login and its own Go subscription."
note "Your existing default identity's key stays at:"
note "  $DEFAULT_AUTH"
note "This wizard never reads, writes or touches that file's key."
open_url "https://opencode.ai"
step "Sign up (or sign in) with a DIFFERENT email than your existing account."
step "Subscribe that account to OpenCode Go."
if ! confirm "Second opencode.ai account created and subscribed to Go?"; then
  warn "Come back once it's subscribed — nothing on this machine changes until then."
  exit 1
fi

# ── Stage 2: an isolated data directory for it ─────────────────────────────
stage "Isolate a data directory for it"
say "opencode reads XDG_DATA_HOME to find its auth.json. Pointing a second"
say "opencode run at a separate XDG_DATA_HOME gives it a separate auth.json —"
say "the same isolation this machine already uses for a second Claude or GLM"
say "account (~/.claude-account2, ~/.claude-glm-2, ...)."

next=2
while [[ -e "$HOME/.opencode-$next" ]]; do
  next=$((next + 1))
done

slot_input=""
printf '  %sSlot number%s %s[Enter for %s]%s ' "$BOLD" "$RESET" "$DIM" "$next" "$RESET"
read -r slot_input || true
SLOT="${slot_input:-$next}"
if ! [[ "$SLOT" =~ ^[0-9]+$ ]]; then
  warn "'$SLOT' isn't a number — using $next instead."
  SLOT="$next"
fi

DATA_HOME="$HOME/.opencode-$SLOT"
AUTH_FILE="$DATA_HOME/opencode/auth.json"

if [[ -f "$AUTH_FILE" ]]; then
  warn "$AUTH_FILE already exists — this slot is already provisioned."
  if ! confirm "Log in again and overwrite it anyway?"; then
    exit 1
  fi
fi

mkdir -p "$DATA_HOME"
note "created $DATA_HOME"

# ── Stage 3: log in under that identity, then verify ───────────────────────
stage "Log in under the new identity, then verify"
say "Run this in another terminal (or here, after this wizard pauses):"
printf '\n    %sXDG_DATA_HOME=%s opencode auth login%s\n\n' "$BOLD" "$DATA_HOME" "$RESET"
step "In the picker, choose OpenCode Go / Zen."
step "Complete the login for the SECOND account you just created."
pause "Done? Press Enter to verify."

if [[ ! -f "$AUTH_FILE" ]]; then
  warn "$AUTH_FILE still doesn't exist. Re-run the login command above, then re-run this wizard."
  exit 1
fi

CHECK=$(DATA_HOME="$DATA_HOME" DEFAULT_AUTH="$DEFAULT_AUTH" AUTH_FILE="$AUTH_FILE" python3 <<'PYEOF'
import json
import os
import sys

auth_file = os.environ["AUTH_FILE"]
default_auth = os.environ["DEFAULT_AUTH"]

try:
    new = json.loads(open(auth_file).read())
except (OSError, ValueError) as e:
    print(f"invalid:{e}")
    sys.exit(0)

entry = new.get("opencode-go")
if not isinstance(entry, dict) or entry.get("type") != "api" or not isinstance(entry.get("key"), str) or not entry["key"]:
    print("missing")
    sys.exit(0)

new_key = entry["key"]
same_as_default = False
try:
    old = json.loads(open(default_auth).read())
    old_entry = old.get("opencode-go")
    if isinstance(old_entry, dict) and old_entry.get("key") == new_key:
        same_as_default = True
except (OSError, ValueError):
    pass

print("same" if same_as_default else "ok")
PYEOF
)

case "$CHECK" in
  ok)
    ;;
  same)
    warn "The key in $AUTH_FILE is identical to your default account's key —"
    warn "this looks like the same account was logged into again, not a second one."
    exit 1
    ;;
  missing)
    warn "$AUTH_FILE exists but has no opencode-go entry yet. Re-run the login command above."
    exit 1
    ;;
  *)
    warn "$AUTH_FILE isn't valid JSON ($CHECK). Re-run the login command above."
    exit 1
    ;;
esac

_clear
printf '\n%s%s  ✓ Second OpenCode Go identity ready%s\n\n' "$BOLD" "$GREEN" "$RESET"
note "data dir:   $DATA_HOME"
note "auth file:  $AUTH_FILE"
printf '\n'
say "Launch opencode against this identity with:"
printf '\n    %sXDG_DATA_HOME=%s opencode ...%s\n\n' "$BOLD" "$DATA_HOME" "$RESET"
warn "unlimited's opencode adapter does not discover ~/.opencode-* yet — that"
warn "code change lands separately; until it does, 'unlimited read' still only"
warn "reports the default account."
printf '\n'
